version: '3.8'

services:
  frontend:
    build: ./drive-plus
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./drive-plus-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./drive-plus-api/database.db:/app/database.db 